import type { Dispute } from '../types/camp'
import { HERO_ARTISAN_ID, HERO_RESIDENT_ID } from '../types/camp'

const daysAgo = (d: number) =>
  new Date(Date.now() - d * 24 * 60 * 60 * 1000).toISOString()

export const seedDisputes: Dispute[] = [
  {
    id: 'dispute-001',
    jobId: 'job-0012',
    residentId: 'resident-mercy-eze',
    artisanId: 'artisan-chiamaka-nwosu',
    status: 'open',
    reason: 'Work incomplete — leak returned after 2 days',
    openedAt: daysAgo(0.6),
    openedBy: 'resident',
    residentStatement:
      'The plumber said the leak was fixed but water still drips under the sink. I paid ₦12,000.',
    artisanStatement: 'I replaced the washer. The resident may have overtightened the pipe.',
    escrowKobo: 1_200_000,
  },
  {
    id: 'dispute-002',
    jobId: 'job-0023',
    residentId: 'resident-joseph-akpan',
    artisanId: 'artisan-olumide-adebayo',
    status: 'open',
    reason: 'Wrong parts installed on generator',
    openedAt: daysAgo(1.2),
    openedBy: 'resident',
    residentStatement: 'He used a cheaper carburetor than what we agreed.',
    artisanStatement: 'The part was equivalent. Resident refused to test before disputing.',
    escrowKobo: 2_200_000,
  },
  {
    id: 'dispute-003',
    jobId: 'job-0031',
    residentId: 'resident-fatima-bello',
    artisanId: 'artisan-emeka-okonkwo',
    status: 'mediating',
    reason: 'Late arrival caused missed appointment',
    openedAt: daysAgo(3),
    openedBy: 'resident',
    residentStatement: 'Electrician arrived 3 hours late. I had already called someone else.',
    artisanStatement: 'Traffic from Lagos. I communicated delay via Bayo.',
    escrowKobo: 1_500_000,
  },
  {
    id: 'dispute-004',
    jobId: 'job-0044',
    residentId: HERO_RESIDENT_ID,
    artisanId: 'artisan-tope-olafemi',
    status: 'mediating',
    reason: 'Paint colour mismatch',
    openedAt: daysAgo(5),
    openedBy: 'resident',
    residentStatement: 'The cream I chose is not what is on the wall.',
    artisanStatement: 'Same bucket code. Lighting makes it look different.',
    escrowKobo: 900_000,
  },
  {
    id: 'dispute-005',
    jobId: 'job-0055',
    residentId: 'resident-chioma-nwosu',
    artisanId: 'artisan-bilkisu-garba',
    status: 'mediating',
    reason: 'Tailor delivered wrong size',
    openedAt: daysAgo(7),
    openedBy: 'resident',
    residentStatement: 'Agbada too tight in the shoulders.',
    artisanStatement: 'Measurements were taken in a rush. Will adjust at no extra cost.',
    escrowKobo: 800_000,
  },
  {
    id: 'dispute-006',
    jobId: 'job-0066',
    residentId: 'resident-samuel-adeyemi',
    artisanId: HERO_ARTISAN_ID,
    status: 'resolved',
    reason: 'Miscommunication on scope',
    openedAt: daysAgo(14),
    openedBy: 'artisan',
    residentStatement: 'I thought fuel filter was included. It was not.',
    artisanStatement: 'Quote was for diagnosis only. Resident agreed verbally.',
    escrowKobo: 1_800_000,
  },
]
