import type { Parish } from '../types/domain'

/** 24 RCCG parishes — shared reference across all surfaces. */
export const parishes: Parish[] = [
  {
    id: 'parish-ikorodu-central',
    name: 'RCCG Ikorodu Central',
    province: 'Lagos Province II',
    pastorName: 'Pastor Ogunleye F.',
    welfareOfficerName: 'Deacon Adeyemi O.',
    monthlyBudgetKobo: 850_000_000,
    currentMonthDisbursedKobo: 428_500_000,
    activeCaseCount: 7,
  },
  {
    id: 'parish-house-on-the-rock-yaba',
    name: 'RCCG House on the Rock - Yaba',
    province: 'Lagos Province I',
    pastorName: 'Pastor M.O.',
    welfareOfficerName: 'Sister Blessing A.',
    monthlyBudgetKobo: 1_200_000_000,
    currentMonthDisbursedKobo: 612_000_000,
    activeCaseCount: 9,
  },
  {
    id: 'parish-throne-of-grace-lekki',
    name: 'RCCG Throne of Grace - Lekki',
    province: 'Lagos Province I',
    pastorName: 'Pastor Emeka Okonkwo',
    welfareOfficerName: 'Brother Tayo Daniels',
    monthlyBudgetKobo: 1_500_000_000,
    currentMonthDisbursedKobo: 890_000_000,
    activeCaseCount: 6,
  },
  {
    id: 'parish-mararaba',
    name: 'RCCG Mararaba',
    province: 'Nasarawa Province',
    pastorName: 'Pastor James Attah',
    welfareOfficerName: 'Deacon Musa Garba',
    monthlyBudgetKobo: 450_000_000,
    currentMonthDisbursedKobo: 198_000_000,
    activeCaseCount: 5,
  },
  {
    id: 'parish-strong-tower-garki',
    name: 'RCCG Strong Tower - Garki',
    province: 'Abuja Province',
    pastorName: 'Pastor David Etim',
    welfareOfficerName: 'Sister Funke O.',
    monthlyBudgetKobo: 980_000_000,
    currentMonthDisbursedKobo: 445_000_000,
    activeCaseCount: 8,
  },
  {
    id: 'parish-open-heavens-surulere',
    name: 'RCCG Open Heavens - Surulere',
    province: 'Lagos Province I',
    pastorName: 'Pastor Kunle Adebisi',
    welfareOfficerName: 'Deacon Wale Ogundimu',
    monthlyBudgetKobo: 720_000_000,
    currentMonthDisbursedKobo: 356_000_000,
    activeCaseCount: 4,
  },
  {
    id: 'parish-city-of-david-vi',
    name: 'RCCG City of David - Victoria Island',
    province: 'Lagos Province I',
    pastorName: 'Pastor Grace Akintola',
    welfareOfficerName: 'Sister Nike Balogun',
    monthlyBudgetKobo: 1_100_000_000,
    currentMonthDisbursedKobo: 520_000_000,
    activeCaseCount: 3,
  },
  {
    id: 'parish-living-spring-ajah',
    name: 'RCCG Living Spring - Ajah',
    province: 'Lagos Province I',
    pastorName: 'Pastor Chidi Nwosu',
    welfareOfficerName: 'Brother Emeka Ibe',
    monthlyBudgetKobo: 650_000_000,
    currentMonthDisbursedKobo: 287_000_000,
    activeCaseCount: 5,
  },
  {
    id: 'parish-salvation-arena-oshodi',
    name: 'RCCG Salvation Arena - Oshodi',
    province: 'Lagos Province II',
    pastorName: 'Pastor Biodun Fashola',
    welfareOfficerName: 'Deacon Yinka Adewale',
    monthlyBudgetKobo: 580_000_000,
    currentMonthDisbursedKobo: 301_000_000,
    activeCaseCount: 6,
  },
  {
    id: 'parish-grace-assembly-berger',
    name: 'RCCG Grace Assembly - Berger',
    province: 'Lagos Province II',
    pastorName: 'Pastor Helen Okafor',
    welfareOfficerName: 'Sister Kemi Ajayi',
    monthlyBudgetKobo: 490_000_000,
    currentMonthDisbursedKobo: 215_000_000,
    activeCaseCount: 4,
  },
  {
    id: 'parish-mercy-seat-egbeda',
    name: 'RCCG Mercy Seat - Egbeda',
    province: 'Lagos Province II',
    pastorName: 'Pastor Solomon Adeyemi',
    welfareOfficerName: 'Brother Femi Olatunji',
    monthlyBudgetKobo: 420_000_000,
    currentMonthDisbursedKobo: 189_000_000,
    activeCaseCount: 5,
  },
  {
    id: 'parish-fountain-of-life-ikeja',
    name: 'RCCG Fountain of Life - Ikeja',
    province: 'Lagos Province II',
    pastorName: 'Pastor Ngozi Eze',
    welfareOfficerName: 'Deacon Chuka Obi',
    monthlyBudgetKobo: 760_000_000,
    currentMonthDisbursedKobo: 398_000_000,
    activeCaseCount: 7,
  },
  {
    id: 'parish-dominion-centre-wuse',
    name: 'RCCG Dominion Centre - Wuse II',
    province: 'Abuja Province',
    pastorName: 'Pastor Ibrahim Musa',
    welfareOfficerName: 'Sister Amina Bello',
    monthlyBudgetKobo: 870_000_000,
    currentMonthDisbursedKobo: 412_000_000,
    activeCaseCount: 6,
  },
  {
    id: 'parish-glory-tabernacle-kubwa',
    name: 'RCCG Glory Tabernacle - Kubwa',
    province: 'Abuja Province',
    pastorName: 'Pastor Matthew Yusuf',
    welfareOfficerName: 'Deacon John Okoro',
    monthlyBudgetKobo: 380_000_000,
    currentMonthDisbursedKobo: 165_000_000,
    activeCaseCount: 3,
  },
  {
    id: 'parish-palace-of-praise-ph',
    name: 'RCCG Palace of Praise - Port Harcourt',
    province: 'Region 24',
    pastorName: 'Pastor Enoch Hart',
    welfareOfficerName: 'Sister Mercy Akpan',
    monthlyBudgetKobo: 620_000_000,
    currentMonthDisbursedKobo: 278_000_000,
    activeCaseCount: 5,
  },
  {
    id: 'parish-jesus-embassy-enugu',
    name: 'RCCG Jesus Embassy - Enugu',
    province: 'Region 24',
    pastorName: 'Pastor Ifeanyi Okafor',
    welfareOfficerName: 'Brother Uche Nnamani',
    monthlyBudgetKobo: 510_000_000,
    currentMonthDisbursedKobo: 234_000_000,
    activeCaseCount: 4,
  },
  {
    id: 'parish-victory-chapel-benin',
    name: 'RCCG Victory Chapel - Benin City',
    province: 'Region 24',
    pastorName: 'Pastor Osagie Igbinedion',
    welfareOfficerName: 'Deacon Efe Omoruyi',
    monthlyBudgetKobo: 440_000_000,
    currentMonthDisbursedKobo: 201_000_000,
    activeCaseCount: 4,
  },
  {
    id: 'parish-mountain-of-fire-ibadan',
    name: 'RCCG Mountain of Fire - Ibadan',
    province: 'Region 24',
    pastorName: 'Pastor Tunde Akinyemi',
    welfareOfficerName: 'Sister Bola Adesanya',
    monthlyBudgetKobo: 550_000_000,
    currentMonthDisbursedKobo: 267_000_000,
    activeCaseCount: 5,
  },
  {
    id: 'parish-ark-of-covenant-abeokuta',
    name: 'RCCG Ark of Covenant - Abeokuta',
    province: 'Region 8',
    pastorName: 'Pastor Joseph Akintunde',
    welfareOfficerName: 'Brother Segun Ogunleye',
    monthlyBudgetKobo: 360_000_000,
    currentMonthDisbursedKobo: 142_000_000,
    activeCaseCount: 3,
  },
  {
    id: 'parish-new-life-kaduna',
    name: 'RCCG New Life Assembly - Kaduna',
    province: 'Region 8',
    pastorName: 'Pastor Hassan Abdullahi',
    welfareOfficerName: 'Deacon Samuel Ibrahim',
    monthlyBudgetKobo: 400_000_000,
    currentMonthDisbursedKobo: 178_000_000,
    activeCaseCount: 4,
  },
  {
    id: 'parish-divine-connection-kano',
    name: 'RCCG Divine Connection - Kano',
    province: 'Region 8',
    pastorName: 'Pastor Yusuf Sani',
    welfareOfficerName: 'Sister Hauwa Mohammed',
    monthlyBudgetKobo: 470_000_000,
    currentMonthDisbursedKobo: 209_000_000,
    activeCaseCount: 4,
  },
  {
    id: 'parish-redemption-camp',
    name: 'RCCG Redemption Camp',
    province: 'Lagos Province I',
    pastorName: 'Pastor Elijah Adegoke',
    welfareOfficerName: 'Deacon Peter Ojo',
    monthlyBudgetKobo: 2_000_000_000,
    currentMonthDisbursedKobo: 1_120_000_000,
    activeCaseCount: 11,
  },
  {
    id: 'parish-holy-ghost-festac',
    name: 'RCCG Holy Ghost Zone - Festac',
    province: 'Lagos Province II',
    pastorName: 'Pastor Collins Eze',
    welfareOfficerName: 'Sister Ada Okeke',
    monthlyBudgetKobo: 530_000_000,
    currentMonthDisbursedKobo: 248_000_000,
    activeCaseCount: 5,
  },
  {
    id: 'parish-bethel-uyo',
    name: 'RCCG Bethel Parish - Uyo',
    province: 'Region 24',
    pastorName: 'Pastor Edidiong Udom',
    welfareOfficerName: 'Brother Anietie Essien',
    monthlyBudgetKobo: 390_000_000,
    currentMonthDisbursedKobo: 171_000_000,
    activeCaseCount: 3,
  },
]

export const PARISH_IKORODU = 'parish-ikorodu-central'
export const PARISH_YABA = 'parish-house-on-the-rock-yaba'

export function getParishById(id: string): Parish | undefined {
  return parishes.find((p) => p.id === id)
}

export function parishesInProvince(province: string): Parish[] {
  return parishes.filter((p) => p.province === province)
}
